// server.js — ONE Node process that (a) serves the static web client and
// (b) runs the authoritative Colyseus game server, on ONE shareable port.
//
// Run:  npm install  &&  node server.js
// Open: the "Network" URL it prints, share that with colleagues on the LAN.
//
// Phase 0 scope: static serving + /health + a scaffold Colyseus room proving
// WebSocket state-sync works on the same port as the static assets.

import { fileURLToPath } from 'node:url';
import path from 'node:path';
import os from 'node:os';
import fs from 'node:fs';
import { createServer } from 'node:http';

import express from 'express';
// colyseus + ws-transport are CommonJS; default-import and destructure (Node
// can't statically detect their named exports for ESM).
import colyseus from 'colyseus';
import wsTransport from '@colyseus/ws-transport';

import { ArenaRoom } from './src/server/rooms/ArenaRoom.js';
import { characterManifest, animsManifest } from './src/server/characters.js';
import { PROTOCOL_VERSION, NET, MODES } from './shared/constants.js';

const { Server } = colyseus;
const { WebSocketTransport } = wsTransport;

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT) || 3000;
const startedAt = Date.now();

const app = express();

// ---------------------------------------------------------------------------
// Caching: during the build phases we serve everything no-store so colleagues
// always get the freshest client on refresh (no "why didn't my change show?").
// Phase 5 will switch vendored libs to long-lived immutable caching for perf.
// ---------------------------------------------------------------------------
app.use((req, res, next) => {
  res.setHeader('Cache-Control', 'no-store');
  next();
});

// ---------------------------------------------------------------------------
// Health check (plain HTTP, handy for `curl` and uptime probes).
// ---------------------------------------------------------------------------
app.get('/health', (req, res) => {
  res.json({
    ok: true,
    phase: 2,
    protocol: PROTOCOL_VERSION,
    uptimeSec: Math.round((Date.now() - startedAt) / 1000),
    now: Date.now(),
  });
});

// ---------------------------------------------------------------------------
// Static client.  public/ is served at "/".
// ---------------------------------------------------------------------------
const staticOpts = { etag: false, lastModified: false, cacheControl: false };
app.use(express.static(path.join(__dirname, 'public'), staticOpts));

// Shared client+server code (single source of truth), served at /shared/*.
app.use('/shared', express.static(path.join(__dirname, 'shared'), staticOpts));

// Third-party art packs (see assets/README.md for license notes). Loaded by
// the client at runtime; the game degrades to procedural scenery without them.
// The character manifest is generated from whatever .glb files exist in
// assets/characters/ — drop a file in and it shows up in the picker.
app.get('/assets/characters/manifest.json', (req, res) => res.json(characterManifest()));
app.get('/assets/anims/manifest.json', (req, res) => res.json(animsManifest()));
app.use('/assets', express.static(path.join(__dirname, 'assets'), staticOpts));

// ---------------------------------------------------------------------------
// Vendored ES-module dependencies — NO external CDNs, fully offline on the LAN.
// We expose only the specific library build dirs we need (not all node_modules).
//   /vendor/three/three.module.js      -> three's single-file ESM build
//   /vendor/three/addons/*             -> three/examples/jsm (GLTFLoader, etc.)
//   /vendor-build/colyseus.esm.js      -> OUR colyseus.js browser bundle
//     (lives in public/vendor-build, generated by scripts/build-vendor.mjs —
//      the npm package ships no artifact that actually runs in a browser)
// (addons mount MUST be registered before the three mount so it wins the prefix)
// ---------------------------------------------------------------------------
app.use('/vendor/three/addons', express.static(path.join(__dirname, 'node_modules/three/examples/jsm'), staticOpts));
app.use('/vendor/three', express.static(path.join(__dirname, 'node_modules/three/build'), staticOpts));

// Self-heal: if the generated bundle is missing (postinstall skipped/cleaned),
// build it now rather than serving a broken client.
{
  const bundlePath = path.join(__dirname, 'public/vendor-build/colyseus.esm.js');
  if (!fs.existsSync(bundlePath)) {
    console.log('[vendor] colyseus browser bundle missing — building…');
    const { buildVendor } = await import('./scripts/build-vendor.mjs');
    await buildVendor();
  }
}

// ---------------------------------------------------------------------------
// Game server: Colyseus bound to the SAME http server -> SAME port.
// ---------------------------------------------------------------------------
const httpServer = createServer(app);
const gameServer = new Server({
  transport: new WebSocketTransport({ server: httpServer }),
});

// joinOrCreate segregates by room name -> one room type per game mode. A full
// room stops being available and the next joiner spins up a fresh one.
//   'arena'    — practice (Phase-2 behaviour; the headless tests join this)
//   'survival' — FFA, limited lives, last one standing
//   'tagteam'  — 5v5, best-of-N rounds
// filterBy('code') keeps parties together: joinOrCreate only matches a room
// whose creation `code` equals the joiner's. Empty code ('') = public quick
// match (everyone groups together up to cap); a shared code = a private room.
gameServer.define(NET.ROOM_ARENA, ArenaRoom, { mode: MODES.PRACTICE }).filterBy(['code']);
gameServer.define(MODES.DM, ArenaRoom, { mode: MODES.DM }).filterBy(['code']);
gameServer.define(MODES.SURVIVAL, ArenaRoom, { mode: MODES.SURVIVAL }).filterBy(['code']);
gameServer.define(MODES.TAGTEAM, ArenaRoom, { mode: MODES.TAGTEAM }).filterBy(['code']);
gameServer.define(MODES.TDM, ArenaRoom, { mode: MODES.TDM }).filterBy(['code']);

gameServer
  .listen(PORT)
  .then(() => printBanner(PORT))
  .catch((err) => {
    console.error('Failed to start server:', err);
    process.exit(1);
  });

// NOTE: no custom SIGINT/SIGTERM handlers — Colyseus registers its own
// graceful shutdown; adding ours double-fires it ("already_shutting_down").

// ---------------------------------------------------------------------------
// Boot banner: prints the LAN URL(s) colleagues should open.
// ---------------------------------------------------------------------------
function lanIPv4s() {
  const out = [];
  const ifaces = os.networkInterfaces();
  for (const name of Object.keys(ifaces)) {
    for (const net of ifaces[name] || []) {
      if (net.family === 'IPv4' && !net.internal) out.push({ name, address: net.address });
    }
  }
  return out;
}

function printBanner(port) {
  const ips = lanIPv4s();
  const line = '='.repeat(60);
  console.log('\n' + line);
  console.log('  TDM Shooter — server running   (Phase 1: movement)');
  console.log(line);
  console.log(`  Local:    http://localhost:${port}`);
  if (ips.length === 0) {
    console.log('  Network:  (no external IPv4 found — are you on Wi-Fi/Ethernet?)');
  } else {
    for (const ip of ips) {
      console.log(`  Network:  http://${ip.address}:${port}   <-- share this  (${ip.name})`);
    }
  }
  console.log(`  Health:   http://localhost:${port}/health`);
  console.log(line);
  console.log('  Colleagues on the same LAN open a "Network" URL in their browser.');
  console.log('  Stop with Ctrl-C.\n');
}
