// scripts/build-vendor.mjs
// Builds the BROWSER bundle of colyseus.js into public/vendor-build/.
//
// Why this exists: colyseus.js 0.15 ships no browser-clean artifact —
//   - dist/colyseus.js (UMD) assumes Node globals (throws "Buffer is not
//     defined" the moment a real browser loads it),
//   - lib/ (the package's "browser" entry) is CommonJS with bare Node deps.
// So we bundle lib/ ourselves with esbuild in browser mode: `ws` resolves to
// its no-op browser shim (native WebSocket is used instead), `httpie` resolves
// to its XHR build, @colyseus/schema inlines cleanly.
//
// The entry is a tiny virtual ESM module re-exporting NAMED exports from the
// CJS package — esbuild's plain CJS->ESM output would otherwise expose only a
// default export ("does not provide an export named 'Client'" in browsers).
//
// After building, the artifact ITSELF is verified (imported and its exports
// type-checked, plus a Node-globals scan) so `npm install` fails loudly
// rather than shipping a client that dies at load.
//
// Runs automatically on `npm install` (postinstall) and self-heals from
// server.js on boot if the artifact is missing. Rebuild manually with:
//   node scripts/build-vendor.mjs

import { build } from 'esbuild';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OUTFILE = path.join(root, 'public/vendor-build/colyseus.esm.js');

// Named API surface we guarantee to the client code.
const NAMED_EXPORTS = ['Client', 'Room', 'Protocol', 'ErrorCode', 'MatchMakeError', 'SchemaSerializer', 'registerSerializer', 'Auth'];

export async function buildVendor({ quiet = false } = {}) {
  const t0 = Date.now();

  // lib/index.js is tsc-emitted CJS with the __esModule marker, so interop of
  // a DEFAULT import yields exports.default === undefined. A namespace import
  // plus a runtime picker works under every interop shape esbuild produces.
  const entry = [
    `import * as NS from './node_modules/colyseus.js/lib/index.js';`,
    `const C = (NS.Client !== undefined) ? NS : (NS.default || NS);`,
    ...NAMED_EXPORTS.map((n) => `export const ${n} = C.${n};`),
    `export default C;`,
  ].join('\n');

  await build({
    stdin: { contents: entry, resolveDir: root, loader: 'js', sourcefile: 'colyseus-entry.js' },
    outfile: OUTFILE,
    bundle: true,
    format: 'esm',
    platform: 'browser',      // honor "browser" fields: ws -> shim, httpie -> xhr
    target: ['es2020'],
    define: { 'process.env.NODE_ENV': '"production"' },
    legalComments: 'none',
    logLevel: 'silent',
    banner: { js: '// colyseus.js browser bundle — generated by scripts/build-vendor.mjs, do not edit' },
  });

  try {
    await verifyArtifact();
  } catch (err) {
    // Never leave a broken artifact for the server to serve.
    fs.rmSync(OUTFILE, { force: true });
    throw err;
  }

  if (!quiet) {
    const kb = Math.round(fs.statSync(OUTFILE).size / 1024);
    console.log(`[vendor] built + verified ${path.relative(root, OUTFILE)} (${kb} KB) in ${Date.now() - t0}ms`);
  }
  return OUTFILE;
}

async function verifyArtifact() {
  // 1. No Node-isms that execute in a browser (the shipped UMD's failure mode).
  const src = fs.readFileSync(OUTFILE, 'utf8');
  for (const bad of [/\brequire\s*\(/, /\bprocess\.versions\b/, /\bBuffer\.from\b/]) {
    if (bad.test(src)) throw new Error(`vendor verify: bundle contains ${bad} — not browser-clean`);
  }

  // 2. Import the REAL artifact (cache-busted so rebuilds re-verify) and
  //    type-check every named export the client relies on.
  const mod = await import(pathToFileURL(OUTFILE).href + `?v=${Date.now()}`);
  const missing = NAMED_EXPORTS.filter((n) => mod[n] === undefined);
  if (missing.length) throw new Error(`vendor verify: named exports missing: ${missing.join(', ')}`);
  for (const n of ['Client', 'Room']) {
    if (typeof mod[n] !== 'function') throw new Error(`vendor verify: export ${n} is not a constructor`);
  }
}

// Invoked directly (postinstall / manual)?
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  buildVendor().catch((err) => {
    console.error('[vendor] build failed:', err.message);
    process.exit(1);
  });
}
